######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 28 09:55:38 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
